chat:
  description: Chat with Poe
  fields:
    name:
      description: Config entity name
      example: poe
      required: true
      selector:
        text:
    bot:
      description: Bot ID
      example: capybara
      required: false
      selector:
        text:
    message:
      description: Message to send
      example: Hello
      required: true
      selector:
        text:
    conversation_id:
      description: Conversation ID
      required: false
      selector:
        text:
    throw:
      description: Throw reply
      default: false
      example: false
      selector:
        boolean:
    throw_chunk:
      description: Throw reply chunked
      default: false
      example: true
      selector:
        boolean:
